import { writeFileSync, mkdirSync } from 'node:fs'
import { resolve, join } from 'node:path'
import { execFileSync } from 'node:child_process'
import type { FlowConfig, RecordingConfig } from './config.js'

/**
 * Generates and runs Playwright test files from config flows.
 * Architecture ref: Section 5 — How record.js works (step 3b).
 *
 * Each flow gets a generated Playwright test file that:
 * - Navigates to baseUrl + flow.path
 * - Waits for the selector specified in the flow config
 * - Executes configured actions (scroll, click, wait)
 * - Holds for the configured duration before closing
 */

export interface ManifestEntry {
  flowName: string
  description: string
  path: string
  recordedAt: string
  durationSeconds: number
  playwrightVideoDir: string
  ffmpegOutputPath: string | null
  mp4OutputPath: string | null
  polishedPath: string | null
}

export class FlowRunner {
  private readonly config: RecordingConfig
  private readonly outputDir: string
  private readonly tempTestDir: string
  // Resolved absolute path to the project root (where wallet-setup.ts lives)
  private readonly projectRoot: string

  constructor(config: RecordingConfig, outputDir: string) {
    this.config = config
    this.outputDir = resolve(outputDir)
    this.projectRoot = resolve(process.cwd())
    this.tempTestDir = join(this.outputDir, '_generated_tests')
    mkdirSync(this.tempTestDir, { recursive: true })
    mkdirSync(join(this.outputDir, 'playwright'), { recursive: true })
  }

  generateTestFile(flow: FlowConfig): string {
    const actionsCode = this.generateActionsCode(flow)
    const walletSetupPath = join(this.projectRoot, 'dist', 'wallet-setup.js')

    // When walletAction is 'connect', use Synpress fixtures with MetaMask.
    // When walletAction is 'none', use plain Playwright test — no wallet needed.
    let testContent: string

    const walletProviderPath = join(this.projectRoot, 'dist', 'src', 'walletProvider.js')

    if (this.config.walletAction === 'inject') {
      // Headless wallet injection via walletProvider module.
      // No MetaMask extension, no display required. Runs from SSH.
      testContent = `
import { test } from '@playwright/test'
import { readWalletConfig, injectWallet, connectWalletOnPage } from '${walletProviderPath.replace(/\\/g, '/')}'

/**
 * Generated test for flow: ${flow.name}
 * ${flow.description}
 * walletAction: inject -- headless EIP-1193 provider, no MetaMask extension.
 */

test('record-${flow.name}', async ({ page }) => {
  // Inject EIP-1193 wallet provider before any navigation
  const walletConfig = readWalletConfig()
  console.log('[flow-runner] Injecting headless wallet (chainId:', walletConfig.chainId, ')')
  const wallet = await injectWallet(page, walletConfig)

  // Anti-detection
  await page.addInitScript(() => {
    Object.defineProperty(navigator, 'webdriver', { get: () => false });
  });
  await page.setExtraHTTPHeaders({
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
  });

  const targetUrl = '${this.config.baseUrl}${flow.path}'
  console.log('[flow-runner] Navigating to:', targetUrl)

  await page.goto(targetUrl, { waitUntil: 'networkidle' })

  console.log(\`[flow-runner] Waiting for selector: ${flow.waitForSelector}\`)
  await page.waitForSelector(\`${flow.waitForSelector}\`, { state: 'attached', timeout: 30_000 })

  // Connect wallet via headless provider
  await connectWalletOnPage(page, wallet)

${actionsCode}

  console.log('[flow-runner] Holding for ${flow.duration} seconds...')
  await page.waitForTimeout(${flow.duration * 1000})

  console.log('[flow-runner] Flow complete: ${flow.name}')
})
`.trim()
    } else if (this.config.walletAction === 'connect') {
      testContent = `
import { testWithSynpress } from '@synthetixio/synpress'
import { metaMaskFixtures } from '@synthetixio/synpress/playwright'
import walletSetup from '${walletSetupPath.replace(/\\/g, '/')}'

/**
 * Generated test for flow: ${flow.name}
 * ${flow.description}
 * Auto-generated by octant-demo-recorder — do not edit manually.
 */

const test = testWithSynpress(metaMaskFixtures(walletSetup))
const { expect } = test

test('record-${flow.name}', async ({ page, metamask }) => {
  // Anti-detection: remove navigator.webdriver flag before any navigation
  await page.addInitScript(() => {
    Object.defineProperty(navigator, 'webdriver', { get: () => false });
  });
  // Anti-detection: set realistic User-Agent (strip HeadlessChrome)
  await page.setExtraHTTPHeaders({
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
  });

  const targetUrl = '${this.config.baseUrl}${flow.path}'
  console.log('[flow-runner] Navigating to:', targetUrl)

  await page.goto(targetUrl, { waitUntil: 'networkidle' })

  // Wait for the primary selector to confirm page is ready
  console.log(\`[flow-runner] Waiting for selector: ${flow.waitForSelector}\`)
  await page.waitForSelector(\`${flow.waitForSelector}\`, { state: 'attached', timeout: 30_000 })

  // Connect MetaMask wallet
  console.log('[flow-runner] Connecting MetaMask wallet')
  await metamask.connectToDapp()

${actionsCode}

  // Hold on final state for the configured duration
  console.log('[flow-runner] Holding for ${flow.duration} seconds...')
  await page.waitForTimeout(${flow.duration * 1000})

  console.log('[flow-runner] Flow complete: ${flow.name}')
})
`.trim()
    } else {
      testContent = `
import { test } from '@playwright/test'

/**
 * Generated test for flow: ${flow.name}
 * ${flow.description}
 * Auto-generated by octant-demo-recorder — do not edit manually.
 * walletAction: none — no MetaMask connection.
 */

test('record-${flow.name}', async ({ page }) => {
  // Anti-detection: remove navigator.webdriver flag before any navigation
  await page.addInitScript(() => {
    Object.defineProperty(navigator, 'webdriver', { get: () => false });
  });
  // Anti-detection: set realistic User-Agent (strip HeadlessChrome)
  await page.setExtraHTTPHeaders({
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
  });

  const targetUrl = '${this.config.baseUrl}${flow.path}'
  console.log('[flow-runner] Navigating to:', targetUrl)

  await page.goto(targetUrl, { waitUntil: 'networkidle' })

  // Wait for the primary selector to confirm page is ready
  console.log(\`[flow-runner] Waiting for selector: ${flow.waitForSelector}\`)
  await page.waitForSelector(\`${flow.waitForSelector}\`, { state: 'attached', timeout: 30_000 })

${actionsCode}

  // Hold on final state for the configured duration
  console.log('[flow-runner] Holding for ${flow.duration} seconds...')
  await page.waitForTimeout(${flow.duration * 1000})

  console.log('[flow-runner] Flow complete: ${flow.name}')
})
`.trim()
    }

    const testFilePath = join(this.tempTestDir, `${flow.name}.spec.ts`)
    writeFileSync(testFilePath, testContent, 'utf-8')
    return testFilePath
  }

  private generateActionsCode(flow: FlowConfig): string {
    if (flow.actions.length === 0) {
      return '  // No actions configured for this flow'
    }

    const lines: string[] = []
    for (const action of flow.actions) {
      switch (action.type) {
        case 'scroll': {
          const scrollY = action.direction === 'down' ? action.amount : -action.amount
          lines.push(`  // Scroll ${action.direction} by ${action.amount}px`)
          lines.push(`  await page.evaluate((y) => window.scrollBy(0, y), ${scrollY})`)
          if (action.delay) {
            lines.push(`  await page.waitForTimeout(${action.delay * 1000})`)
          }
          break
        }
        case 'click': {
          lines.push(`  // Click: ${action.selector}`)
          lines.push(`  await page.click(\`${action.selector}\`)`)
          if (action.delay) {
            lines.push(`  await page.waitForTimeout(${action.delay * 1000})`)
          }
          break
        }
        case 'wait': {
          lines.push(`  // Wait ${action.duration} seconds`)
          lines.push(`  await page.waitForTimeout(${action.duration * 1000})`)
          break
        }
        case 'navigate': {
          lines.push(`  // Navigate to: ${action.path}`)
          lines.push(`  await page.goto(\`${this.config.baseUrl}${action.path}\`, { waitUntil: 'networkidle' })`)
          if (action.waitForSelector) {
            lines.push(`  await page.waitForSelector(\`${action.waitForSelector}\`, { state: 'attached', timeout: 30_000 })`)
          }
          if (action.delay) {
            lines.push(`  await page.waitForTimeout(${action.delay * 1000})`)
          }
          break
        }
        case 'type': {
          lines.push(`  // Type into: ${action.selector}`)
          lines.push(`  await page.fill(\`${action.selector}\`, \`${action.text}\`)`)
          if (action.delay) {
            lines.push(`  await page.waitForTimeout(${action.delay * 1000})`)
          }
          break
        }
        case 'screenshot': {
          lines.push(`  // Screenshot: ${action.name}`)
          lines.push(`  await page.screenshot({ path: \`${this.outputDir}/screenshots/${flow.name}_${action.name}.png\`, fullPage: false })`)
          break
        }
      }
    }

    return lines.join('\n')
  }

  async runFlow(flow: FlowConfig): Promise<void> {
    const testFilePath = this.generateTestFile(flow)
    console.log(`[flow-runner] Running flow: ${flow.name}`)
    console.log(`[flow-runner] Generated test: ${testFilePath}`)

    try {
      execFileSync(
        join(this.projectRoot, 'node_modules', '.bin', 'playwright'),
        ['test', `${flow.name}.spec.ts`, '--reporter=list'],
        {
          cwd: this.projectRoot,
          stdio: 'inherit',
          env: {
            ...process.env,
            PLAYWRIGHT_TEST_DIR: this.tempTestDir,
            BASE_URL: this.config.baseUrl,
            PLAYWRIGHT_VIDEOS_DIR: join(this.outputDir, 'playwright', flow.name),
          },
          // 10-minute buffer — MetaMask wallet setup + extension loading can be slow on first run
          timeout: (flow.duration + 600) * 1000,
        }
      )
    } catch (err) {
      throw new Error(
        `Flow "${flow.name}" failed: ${err instanceof Error ? err.message : String(err)}`
      )
    }
  }
}
